

reporting_categories <- tribble(
  ~ event_type, ~ reporting_standard, 
"Astronomical low tide", "impact, noteworthiness, public interest", 
  "Avalanche" , "impact, noteworthiness, public interest",  
"Coastal Flood ", "impact, noteworthiness, public interest" ,
"  Dense Fog ", "impact, noteworthiness, public interest" ,
"Dense Smoke ", "impact, noteworthiness, public interest" ,
   "Dust Devil ", "impact, noteworthiness, public interest" ,
   "Dust Storm ","impact, noteworthiness, public interest",
   "Flash Flood", "impact, noteworthiness, public interest",
   "Flood", "impact, noteworthiness, public interest" ,
   "Freezing Fog", "impact, noteworthiness, public interest" , 
   "Funnel Cloud" , "impact, noteworthiness, public interest" ,
   "Freezing Fog" , "impact, noteworthiness, public interest" ,
   "Funnel Cloud" , "impact, noteworthiness, public interest" ,
   "Heavy Rain" , "impact, noteworthiness, public interest" ,
   "High Surf" , "impact, noteworthiness, public interest" , 
   "Lakeshore Flood" , "impact, noteworthiness, public interest" ,
   "Lightning" , "impact, noteworthiness, public interest" ,
   "Marine Dense Fog" , "impact, noteworthiness, public interest" ,
   "Marine Hail" , "impact, noteworthiness, public interest" ,
   "Marine Heavy Freezing Spray" , "impact, noteworthiness, public interest" ,
   "Marine High Wind" , "impact, noteworthiness, public interest" ,
   "Marine Hurricane/Typhoon","impact, noteworthiness, public interest" , 
   "Marine Lightning" , "impact, noteworthiness, public interest" ,
   "Marine Strong Wind" , "impact, noteworthiness, public interest" ,
   "Marine Thunderstorm Wind" , "impact, noteworthiness, public interest" ,
   "Marine Tropical Depression" , "impact, noteworthiness, public interest" ,
   "Marine Tropical Storm" , "impact, noteworthiness, public interest" ,
   "Rip Currents" , "impact, noteworthiness, public interest" ,
   "Seiche" , "impact, noteworthiness, public interest" ,
   "Sneaker Wave" , "impact, noteworthiness, public interest" ,
   "Storm Surge/Time" , "impact, noteworthiness, public interest", 
   "Strong Wind ", "impact, noteworthiness, public interest" , 
   "Thunderstorm Wind" , "impact, noteworthiness, public interest" ,
   "Tsunami" , "impact, noteworthiness, public interest" ,
   "Volcanic Ash" , "impact, noteworthiness, public interest" ,
   "Wildfire" , "impact, noteworthiness, public interest" ,
   "Winter Weather" , "impact, noteworthiness, public interest",
"Blizzard", "intensity",
"Cold/Wind Chill ", "intensity",
"Debris Flow", "intensity",
"Excessive Heat", "intensity",
"Extreme Cold/Wind Chill", "intensity",
"Frost", "intensity",
"Hail", "intensity",
"Heat", "intensity",
"Heavy Snow", "intensity",
"High Wind ", "intensity",
"Hurricnae/Typhoon", "intensity",
"Ice Storm", "intensity",
"Lake Effect Snow", "intensity",
"Sleet", "intensity",
"Tornado", "intensity",
"Tropical Depression", "intensity",
"Tropical Storm", "intensity",
"Waterspout", "intensity",
"Winter Storm", "intensity"
)

