---
title: "Writing Workshop Day 4"
output:
  pdf_document: default
  word_document: default
  html_document: default
---

# 2. Identify claims in the example papers.
Re-read the two first paragraphs in the Chelygina et al. paper. Highlight a single claim that you think is the most important claim made in this section:

"Twitter is one of the most popular social media platforms, with over 320 million active users as of February 2019. Twitter users can enjoy free content delivered by other users whom they actively decide to follow. **However, unlike in other areas where Twitter is used passively (e.g., to follow influential figures and/or information agencies), in science it can be used in a much more active, collaborative way: to ask for advice, to form new bonds and scientific collaborations, to announce jobs and find employees, to find new mentors and jobs.** This is particularly important in the early stages of a scientific career, during which lack of collaboration or delayed access to information can have the most impact.

“For these reasons, using Twitter appropriately [1] can be more than just a social media activity; it can be a real career incubator in which researchers can develop their professional circles, launch new research projects and get helped by the community at various stages of the projects. Twitter is a tool that facilitates decentralization in science; you are able to present yourself to the community, to develop your personal brand, to set up a dialogue with people inside and outside your research field and to create or join professional environment in your field without mediators such as your direct boss.”

Re-read the following paragraph in the Gall et al. paper. Highlight a single claim that you think is the most important claim in this paragraph:

“**A more subtle form of introducing hazard bias arises from issues of the definition of the hazard and assigning loss estimates (by the original data source) to predefined hazard categories within a database**. This is most apparent in the management of complex events involving multiple hazards versus a singular hazard event. A tornado spawned by a hurricane is counted as a unique tornado event, but it could also be lumped together within the entire hurricane event, or both. Each loss database classifies events differently, especially when they involve multiple hazard types (Guha-Sapir and Below 2002). Inconsistent naming conventions and classification methodologies aggravate this problem and can result in different (and/ or artificial) hazard categories for similar, if not identical events. For example, Downton et al. (2005) reveal a $520 million”flood" loss in FEMA’s database that was not in the NWS data. The discrepancy is a result of differences in how each agency defines what constitutes a flood event. In this case, the event (storm surge) was outside NWS’s definition of a flood."  

Page 123 of The Craft of Research gives several categories for types of claims. What type of claim do you think is being made in each of the two paragraphs above? Do you think each is more conceptual or more practical? Does this agree with the surrounding content of the paper (i.e., is it trying to change the readers mind or trying to make the reader do something)? Do either of the claims include a hedge or qualification?

* Twitter- 
    - making a claim of action or policy (claiming that scientists should use twitter in a certain way)   
    - this claim is more practical, it is trying to get the reader to take action to change the way they use twitter  
    - this claim contains a qualification about how twitter is usually used passively, but in this case could be used actively  
    
* Losses-  
    - making a claim of definition and classification (claiming another way that hazard bias arises in the databases)  
    - this claim is more conceptual as it is about what hazard bias and how it shows up  
    - it seems that this paragraph is mostly trying to educate the reader on how they see a certain issue  
    - this claim does not contain a hedge or qualification  
    
# 3. Identify and revise a claim in your manuscript.
Pick a paragraph of your manuscript where you are making an important claim. Highlight the sentence that makes the key claim in that paragraph.

Based on Chapter 8 of The Craft of Research, describe and assess this claim. What type of claim is it (see p. 123)? Is it practical or conceptual? Is it too weak or too strong, given what you think you can reasonable claim based on your evidence and logic? Is the claim specific? Is your claim significant?

Revise the claim based on your assessment. If you are trying to get the readers to do something with your paper, make sure it is a claim of action. If you are trying to change readers minds, make sure it is a conceptual claim. If it seems too weak, see if there are any hedges or qualifications that should be taken out. If it instead seems too strong, consider adding these.  

**More temporal bias may be showcased on a short term scale by seasonal differences in number of events reported for certain storm types.** For example, NOAA exhibits higher rates of rip currents in the summer versus the winter although the probablity of a rip current occuring during summer may not be inherently higher. It may be that more people attend the beach and swim in the ocean during the summer and are thus more likely to experience and/or report a rip current. A study completed by Gensini and Ashley found that "summer season weekends are shown to have the more [rip current] fatalities than any other time of the year" [@gensini2010examination].  

* I think this is a claim of cause or consequence because I am arguing that seasonal differences in reporting leads to more temporal bias. I back up this claim with the rip current example. This claim is conceptual as I am trying to change the reader's mind about the reason behind elevated event recordings during certain times of the year. However, my claim seems weak as it is written now but is still significant.  

Revised: Although certain weather events truly exhibit seasonal differences in their meteorology, other factors related to temporal bias may artificially inflate or deflate the number of certain events recorded throughout the year. 

# 4. Identify evidence, reasons, acknowledgments in example papers.
Re-read the two first paragraphs in the Chelygina et al. paper:

"Twitter is one of the most popular social media platforms, with over 320 million active users as of February 2019. Twitter users can enjoy free content delivered by other users whom they actively decide to follow. However, unlike in other areas where Twitter is used passively (e.g., to follow influential figures and/or information agencies), in science it can be used in a much more active, collaborative way: to ask for advice, to form new bonds and scientific collaborations, to announce jobs and find employees, to find new mentors and jobs. This is particularly important in the early stages of a scientific career, during which lack of collaboration or delayed access to information can have the most impact.

“For these reasons, using Twitter appropriately [1] can be more than just a social media activity; it can be a real career incubator in which researchers can develop their professional circles, launch new research projects and get helped by the community at various stages of the projects. Twitter is a tool that facilitates decentralization in science; you are able to present yourself to the community, to develop your personal brand, to set up a dialogue with people inside and outside your research field and to create or join professional environment in your field without mediators such as your direct boss.”

Based on the key claim you identified earlier for these paragraphs, write down the reasons that the text gives to support that claim. Write these down by first writing the claim in bold and then providing a bulleted list with each key reason they give in support of that claim (you can put these in the order they’re given in the text, but you don’t have to).  

**However, unlike in other areas where Twitter is used passively (e.g., to follow influential figures and/or information agencies), in science it can be used in a much more active, collaborative way: to ask for advice, to form new bonds and scientific collaborations, to announce jobs and find employees, to find new mentors and jobs.**   

* using Twitter appropriately [1] can be more than just a social media activity    
* Twitter is a tool that facilitates decentralization in science  


Assess these reasons. What evidence do they give in support of these reasons? Are there any where they assume that no evidence is needed, because the reason is commonly accepted as valid? Can you identify any qualifications / acknowledgments that are included in their argument in support of the key claim or any of the reasons they provide for the main claim?

These seem like examples of anecdotal evidence: 

1st claim:  

* career incubator in which researchers can develop their professional circles  
* launch new research projects    
* get helped by the community at various stages of the projects    

2nd claim:  

* twitter is a tool that facilitates decentralization in science    
* you are able to present yourself to the community    
* to develop your personal brand    
* to set up a dialogue with people inside and outside your research field  
* create or join professional environment in your field without mediators such as your direct boss  

I don't see examples of qualifications or aknowledgments used in the argument. I only see the one used in the main claim.  

Re-read the following paragraph in the Gall et al. paper. Highlight a single claim that you think is the most important claim in this paragraph:  

“**A more subtle form of introducing hazard bias arises from issues of the definition of the hazard and assigning loss estimates (by the original data source) to predefined hazard categories within a database.** This is most apparent in the management of complex events involving multiple hazards versus a singular hazard event. A tornado spawned by a hurricane is counted as a unique tornado event, but it could also be lumped together within the entire hurricane event, or both. Each loss database classifies events differently, especially when they involve multiple hazard types (Guha-Sapir and Below 2002). Inconsistent naming conventions and classification methodologies aggravate this problem and can result in different (and/ or artificial) hazard categories for similar, if not identical events. For example, Downton et al. (2005) reveal a $520 million”flood" loss in FEMA’s database that was not in the NWS data. The discrepancy is a result of differences in how each agency defines what constitutes a flood event. In this case, the event (storm surge) was outside NWS’s definition of a flood."

Based on the key claim you identified earlier for these paragraphs, write down the reasons that the text gives to support that claim. Write these down by first writing the claim in bold and then providing a bulleted list with each key reason they give in support of that claim (you can put these in the order they’re given in the text, but you don’t have to).  

**A more subtle form of introducing hazard bias arises from issues of the definition of the hazard and assigning loss estimates (by the original data source) to predefined hazard categories within a database.**  

* This is most apparent in the management of complex events involving multiple hazards versus a singular hazard event    
* Inconsistent naming conventions and classification methodologies aggravate this problem and can result in different (and/ or artificial) hazard categories for similar, if not identical events  


Assess these reasons. What evidence do they give in support of these reasons? Are there any where they assume that no evidence is needed, because the reason is commonly accepted as valid? Can you identify any qualifications / acknowledgments that are included in their argument in support of the key claim or any of the reasons they provide for the main claim?  

Evidence for 1st claim:  

* A tornado spawned by a hurricane is counted as a unique tornado event, but it could also be lumped together within the entire hurricane event, or both  
*  Each loss database classifies events differently, especially when they involve multiple hazard types (Guha-Sapir and Below 2002)  

Evidence for 2nd claim:  

* For example, Downton et al. (2005) reveal a $520 million”flood" loss in FEMA’s database that was not in the NWS data. The discrepancy is a result of differences in how each agency defines what constitutes a flood event. In this case, the event (storm surge) was outside NWS’s definition of a flood."

I again don't see any qualifications or acknowledgements included in their argument. 

# 6. Identify evidence, reasons, and acknowledgments in example papers.
Use the paragraph from your manuscript that you used for prompt 3. Write out the key claim and the reasons you give to support it, using the same style as for the last prompt.

Evaluate these reasons using the same questions as in the last prompt. What evidence do you give in support of these reasons? Are there any where you assume that no evidence is needed, because the reason is commonly accepted as valid? Are there any qualifications / acknowledgments that are included in their argument in support of the key claim or any of the reasons you provide for the main claim?

Revise the paragraph based on your assessment. If there are areas where you need more reasons or evidence, you can put placeholders in to note what’s missing and do more research later to fill those in.

Although certain weather events truly exhibit seasonal differences in their meteorology, other factors related to temporal bias may artificially inflate or deflate the number of certain events recorded throughout the year. For example, NOAA exhibits higher rates of rip currents in the summer versus the winter although the probablity of a rip current occuring during summer may not be inherently higher. It may be that more people attend the beach and swim in the ocean during the summer and are thus more likely to experience and/or report a rip current. A study completed by Gensini and Ashley found that "summer season weekends are shown to have the more [rip current] fatalities than any other time of the year" [@gensini2010examination].  

Revised: **Although certain weather events truly exhibit seasonal differences in their meteorology, other factors related to temporal bias may artificially inflate or deflate the number of certain events recorded throughout the year.**   
Reason:  

* the probablity of a rip current occuring during summer may not be inherently higher  

Evidence:  

* It may be that more people attend the beach and swim in the ocean during the summer and are thus more likely to experience and/or report a rip current

In this paragraph it seems like I jump right into an example before clearly defining a reason that supports my claim. Additionally, I definitely need to add in more reasons and evidence in this paragraph for my claim. 

Revised: 
Although certain weather events truly exhibit seasonal differences in their meteorology, other factors related to temporal bias may artificially inflate or deflate the number of certain events recorded throughout the year. One of these factors is how the timing of a weather event's hazardous outcomes could attract more attention. For example, NOAA exhibits higher rates of rip currents in the summer versus the winter.  Additionally, a study completed by Gensini and Ashley found that "summer season weekends are shown to have the most [rip current] fatalities than any other time of the year" [@gensini2010examination].However, the probablity of a rip current occuring during summer may not be inherently higher. It may be that more people attend the beach and swim in the ocean during the summer and are thus more likely to experience and/or report a rip current. Humans experience the hazardous outcome more in the summer and thus will be more likely to report it. 

Looking into the actual seasonality of rip currents:  

* Direct quote: The strength of rip currents can be seasonal. During hurricane season (from June to November) there is a greater chance for rip currents to develop.[@natgeo]  
* Rip currents are related to several envrionmental factors including waves (surf heights, period, direction), beach (slope, orientation, material), water levels (tidal cycle, tide ranges), winds (affect wave breaking) and wind-driven currents alongshore, others like local coastal configuration and beach and promontories by natural or human made. [@nwsripcurrent]  
* "The most likely scenario for rip hazards is not high surf but high exposure of beachgoers in the warm water of the summer-fall period. When low-energy, longer-period waves (significant wave heights of 0.5 -1.5 meters in 10-15 second sequences) lead to the highest number of rip incidents. During spring/neap tides or very low daily tidal cycles, a mass rescue event can occur, with hundreds of rescues in several locations on a beach, or at several beaches under the same conditions." [@nwsripcurrent]  
* "societal factors (e.g., weekends and holidays) that could change the risk of a rip current fatality. For example, low and high pressure systems off the east coast of the United States can produce onshore flow to many surf zones. Both systems may invoke a high rip current formation risk on the LURCS, but swimmers will be more inclined to enter the water on days when a high pressure system is offshore. The clear skies generally associated with large-scale subsidence of a high pressure system would provide beachgoers with favorable weather for beach activities as opposed to a day amid a low pressure system with stratus clouds and precipitation occurring" [@gensini2010examination]   

I also want to bring in the other example using frost: 
Frost event listings are particularly high at the start and end of the frost season, rather than in the middle of winter, which may be related to the impacts of frost on crops being higher in spring and fall than during the winter.

I still need to add in research about the seasonality of frost events. 

  
# 8. Add a warrant in an example paper.  

In the Chelygina et al. paper, the claim is made that:

“Using Twitter appropriately … can be a real career incubator”

One of the reasons that they give is:

“In science [Twitter] can be used in a much more active, collaborative way: to ask for advice, to form new bonds and scientific collaborations, to announce jobs and find employees, to find new mentors and jobs.”

To connect this reason with their claim, they provide the following warrant:

“This is particularly important in the early stages of a scientific career, during which lack of collaboration or delayed access to information can have the most impact.”

Explain how this warrant connects this reason to the key claim they make.  

* This warrant connects their reason and key claim because it explains how collaboration could advance a scientist's career. It also shows how, in general, external factors can have a large effect on a career.  

Another of the reasons that they give, but for which they do not provide a warrant, is:

“Twitter users can enjoy free content delivered by other users whom they actively decide to follow.”


Rewrite the first two paragraphs of their introduction to add a warrant connecting this reason to the main claim.

Revised: Twitter is one of the most popular social media platforms, with over 320 million active users as of February 2019. Twitter users can enjoy free content delivered by other users whom they actively decide to follow. **Following other users on Twitter allows for access to a broad set of information and the ability to make connections with other users.** Twitter is typically used passively to follow influential figures and/or information agencies. However, in science it can be used in a much more active, collaborative way: to ask for advice, to form new bonds and scientific collabora- tions, to announce jobs and find employees, to find new mentors and jobs. This is particularly important in the early stages of a scientific career, during which lack of collaboration or delayed access to information can have the most impact.  

For these reasons, using Twitter appropriately [1] can be more than just a social media activity; it can be a real career incubator in which researchers can develop their professional circles, launch new research projects and get helped by the community at various stages of the projects. Twitter is a tool that facilitates decentralization in science; you are able to present yourself to the community, to develop your personal brand, to set up a dialogue with people inside and outside your research field and to create or join professional environment in your field without mediators such as your direct boss.

Do you think this added warrant is necessary, or will it be clear to most readers how they connect without it?  

* I don't think this warrant is 100% necessary because it makes sense that following users gives you free content. However, it helps to clarify why bringing up that point is important to the rest of the argument.  

# 9. Add warrants to your manuscript.  

Revisit the paragraph from your manuscript that you used for prompts 3 and 6. Do you give a warrant for every reason that you provide for your key claim in that paragraph? If not, pick the warrant-less reason for which you think the connection will be the least obvious for reader and add a warrant.  

Although certain weather events truly exhibit seasonal differences in their meteorology, other factors related to temporal bias may artificially inflate or deflate the number of certain events recorded throughout the year. One of these factors is how the timing of a weather event's hazardous outcomes could attract more attention. **The media and the public are more likely to report a weather event when it directly physically affects them.** One example of this occurs with rip currents. NOAA exhibits higher rates of rip currents in the summer versus the winter. Gensini and Ashley also found that "summer season weekends are shown to have the most [rip current] fatalities than any other time of the year" [@gensini2010examination]. However, the probablity of a rip current occuring during summer or on the weekend may not be inherently higher. It may be that more people attend the beach and swim in the ocean during the summer and on the weekends and are thus more likely to experience and/or report a rip current. Humans experience the hazardous outcome more in the summer and thus will be more likely to report it during that time. 


In re-reading the paragraph, do you think this warrant is useful or unnecessary? Skim through other paragraphs in your manuscript and find 2–3 other places where a warrant might be helpful and add one.  

I think that this warrant is very useful in tying together what I am trying to get across. It helps the reader understand how the higher number of rip currents could be due to human attention rather than meterology.  

